language: node_js
node_js:
  - "8.1"
  - "lts/*"
  - "node"
env:
  global:
    - BING_KEY=0
    - NEWS_KEY=0
    - NYT_KEY=0
script:
  - node index.js
  - node cacheFunctions index.js
  - node cacheFunctions hacktivity.js
